### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by abdurrahmanekr** [serhatboyraz/bibilgimobile#1]
- [x] **Uygulama lisanslanacak**
- [x] Uygulamanın main ekranı düzenlenecek ve bind edilecek
- [x] İos & android uyumsuzlukları test edilecek
- [x] Setting sayfası yazılacak
- [x] favorilerim eklenecek
- [x] Klasör yapısı hakkında readme.md yazılacak
- [x] Bu uygulama hakkında kısa bir blog yazısı veya reklam yapılacak
- [ ] Push notification test edilecek

Dikkat buradaki bir işi tamamladıysanız bitirdiğinizi işaretleyiniz ve attığınız commit'leri buraya yorum olarak atınız.

**Comment by abdurrahmanekr** [comment]
#985bd1a lisans eklendi

**Comment by abdurrahmanekr** [comment]
Çoğu kısım bitti sadece servis ile bağlantı yapılacak yerler kaldı onu da buraya ekledim #2 
Bu issue'da ürünün açıklama kısımlarını bitirmekle alakalı şeyler kaldı o kadar.

**Comment by abdurrahmanekr** [comment]
Uygulamanın blog yazısı hazır: [http://www.avarekodcu.com/konu/25/...uygulamasi-bibilgi-acik-kaynak-projesi](http://www.avarekodcu.com/konu/25/react-native-ile-ilginc-bilgiler-uygulamasi-bibilgi-acik-kaynak-projesi)

**Comment by abdurrahmanekr** [comment]
Uzun süre uğraşılmadığı için kapatıyorum.
