### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by abdurrahmanekr** [serhatboyraz/bibilgimobile#2]
- [x] Favorilerimi kaydetmek için SqLite kullanılacak
- [x] Detaylı bilgi için sayfa oluşturulacak
- [x] Paylaş butonu çalışır hale getirilecek

> [Dennis Ritchie](https://github.com/dspinellis/unix-history-repo)'i yad ediyoruz 🙏
